{% set name = "vollseg" %}
{% set version = "5.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vollseg-{{ version }}.tar.gz
  sha256: 0f9d6b23c8ddd4bac57e79681fe0bf0426b53f716aa8f68be7f1911d825d8f3a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - diplib-python
    - matplotlib-base
    - napari
    - opencv
    - pandas
    - scipy
    - stardist >=0.7.0
    - tifffile
    - csbdeep
    - tensorflow

test:
  imports:
    - vollseg
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kapoorlab/vollseg/
  summary: Segmentation tool for biological cells of irregular size and shape in 3D and 2D.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - kapoorlab
