{% set name = "vollseg" %}

{% set version = "5.6.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vollseg-{{ version }}.tar.gz
  sha256: 5ec7de7e8d408e5497ce250902294f91ea9c35640aa7f3238379debaabe626a4
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - diplib-python
    - matplotlib-base
    - napari
    - opencv
    - pandas
    - scipy
    - stardist >=0.7.0
    - tifffile
    - csbdeep
    - tensorflow
    - photutils

test:
  imports:
    - vollseg
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kapoorlab/vollseg/
  summary: Segmentation tool for biological cells of irregular size and shape in 3D and 2D.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - kapoorlab
