{% set name = "vollseg" %}


{% set version = "5.9.9" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vollseg-{{ version }}.tar.gz

  sha256: 6ca87bc3e621a8dacc220fb7fc784e2e2a6d3b9a399ebe63c641d09b312e2faa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - diplib
    - matplotlib-base
    - napari
    - pandas
    - scipy
    - stardist >=0.7.0
    - tifffile
    - csbdeep
    - tensorflow


test:
  imports:
    - vollseg
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kapoorlab/vollseg/
  summary: Segmentation tool for biological cells of irregular size and shape in 3D and 2D.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - kapoorlab
