{% set name = "vollseg" %}


{% set version = "5.7.3" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vollseg-{{ version }}.tar.gz

  sha256: 80b26862c345d7850161acb3ec66f84b0e7a3e4ce8dd746c05b075bb94032a67

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - diplib-python
    - matplotlib-base
    - napari
    - opencv
    - pandas
    - scipy
    - stardist >=0.7.0
    - tifffile
    - csbdeep
    - tensorflow
    - photutils
    - albumentations

test:
  imports:
    - vollseg
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kapoorlab/vollseg/
  summary: Segmentation tool for biological cells of irregular size and shape in 3D and 2D.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - kapoorlab
