{% set name = "vollseg" %}


{% set version = "5.9.6" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vollseg-{{ version }}.tar.gz

  sha256: 2b73d5c8eb5e3cf1afba074818c420e887fa59559e67ded1f364d17f50bf99b3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - diplib
    - matplotlib-base
    - napari
    - pandas
    - scipy
    - stardist >=0.7.0
    - tifffile
    - csbdeep
    - tensorflow


test:
  imports:
    - vollseg
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kapoorlab/vollseg/
  summary: Segmentation tool for biological cells of irregular size and shape in 3D and 2D.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - kapoorlab
